### ISSUE TITLE
Welcome screen in dark mode unreadable

### ISSUE THREAD

**Issue by vancha** [0xZhangKe/FreadIssueTracker#2]
Looks like the welcome screen doesn't like dark mode, this is what it looked like on my pixel 6a running android 14:

## image
![Screenshot_20240813-090231(1)](https://github.com/user-attachments/assets/548ee3d0-eebf-4f9d-8911-2e597c84b337)

The dark text on a dark background is illegible. It would have been solved with a higher contrast ratio.

**Comment by 0xZhangKe** [comment]
Ok, thanks for the reminder, I will fix it in the next version.
