### ISSUE TITLE
Alt text view option for images 

### ISSUE THREAD

**Issue by emsquarial** [0xZhangKe/FreadIssueTracker#5]
Request please for the option to view which images in a timeline have alt text added to and image and the ability to view that descriptive text as this is important to limited or non sighted users.
Many thanks.

**Comment by 0xZhangKe** [comment]
@emsquarial Hello, this is my oversight. I will improve this feature in future versions. Thanks for your reminder.

**Comment by emsquarial** [comment]
Many thanks. App shows a lot of promise and this is the only thing I could point to that stops me using it full time. Best wishes.

**Comment by 0xZhangKe** [comment]
@emsquarial Hello, thank you for your suggestion. I have released the latest version 1.1.4 these days. This version solves the problem you mentioned. Please update to the latest version and try again. If you have any questions, please let me know.

**Comment by emsquarial** [comment]
Brilliant. Many thanks.
