### ISSUE TITLE
1.部分RSS订阅内容不全；2.关于长毛象站点

### ISSUE THREAD

**Issue by DHONEST** [0xZhangKe/FreadIssueTracker#6]
如题

1.显示不全的是豆豉站站长的博客，同步内容只到2020年，近期文章刷不出来，用feeder就不会这样。订阅的博客不多，目前只遭遇了这一例。

2.O3O站提供了免翻墙域名，但是这边应用只有o3o.ca本站（镜像站访问令牌无效），一应内容只有翻墙可看，不如网页刷得顺手。

**Comment by 0xZhangKe** [comment]
@DHONEST 
1. 近期文章不显示已经修复了，更新到最新版再试试看。
2. 这种处理起来比较麻烦，后面我在想办法兼容吧。
